remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

baseurl: "/Study-Site"

title: A Study on LLMs
repository: XanderAP25/Study-Site

markdown: kramdown
kramdown:
  footnotes: true

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Article
    url: /article/
  - title: Stories
    url: /stories/
  - title: Notebooks
    url: /notebooks/
  - title: Text Analysis Notebook
    url: /text_analysis_notebook/
  - title: Finetune Notebook
    url: /notebook_notebook/
sass:
  sass_dir: _sass
  style: compressed

