remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: A Study on LLMs
repository: XanderAP25/Study-Site

markdown: kramdown
kramdown:
  footnotes: true

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Article
    url: /article/
  - title: Stories
    url: /stories/
  - title: Notebook
    url: /notebook/
sass:
  sass_dir: _sass
  style: compressed

