remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

baseurl: "/Study-Site"

title: A Study on LLMs
repository: XanderAP25/Study-Site

markdown: kramdown
kramdown:
  footnotes: true

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Stories
    url: /stories/
  - title: Case Study
    url: /case_study/
  - title: A Guide to LLMs
    url: "#"
    sublinks:
      - title: Introduction to AI and LLMs
        url: /intro_to_ai_and_llms.html
      - title: How LLMs Benefit You and Their Challenges
        url: /how_llms_benefit_you_and_their_challenges.html
      - title: Training and Fine-Tuning an LLM
        url: /training_and_fine_tuning_an_llm.html
      - title: Making LLMs Work for You
        url: /making_llms_work_for_you.html
sass:
  sass_dir: _sass
  style: compressed

